export const TWITTER_AUTH_SUCCESS = 'TWITTER_AUTH_SUCCESS'
export const TWITTER_AUTH_FAIL = 'TWITTER_AUTH_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
